
- hosts: localhost
  gather_facts: no
  tasks:


    - name: "Create flavors"
      os_nova_flavor: state={{ item.state }} name={{ item.name }} ram={{ item.ram }} vcpus={{ item.vcpus }} disk={{ item.disk }} ephemeral={{ item.ephemeral }} flavorid={{ item.flavorid }}
      with_items:
        - { state: 'present', name: 'LB' , ram: '4096' , vcpus: '1' , disk: '0' , ephemeral: '0' , flavorid: '10' }
        - { state: 'present', name: 'Master' , ram: '16384' , vcpus: '2' , disk: '0' , ephemeral: '0' , flavorid: '6' }
        - { state: 'present', name: 'Infra' , ram: '16384' , vcpus: '2' , disk: '0' , ephemeral: '0' , flavorid: '7' }
        - { state: 'present', name: 'App' , ram: '16384' , vcpus: '2' , disk: '0' , ephemeral: '0' , flavorid: '8' }
        - { state: 'present', name: 'Bastion' , ram: '4096' , vcpus: '1' , disk: '0' , ephemeral: '0' , flavorid: '9' }
    - name: Create OCP cluster
      include: ./tasks/rhel-instance-docker-provider.yml
      with_items:
        - { instancename: 'master1', flavor: 'master', volume_size: '50' }
        - { instancename: 'master2', flavor: 'master', volume_size: '50' }
        - { instancename: 'master3', flavor: 'master', volume_size: '50' }
        - { instancename: 'infra1', flavor: 'infra', volume_size: '50' }
        - { instancename: 'infra2', flavor: 'infra', volume_size: '50' }
        - { instancename: 'app', flavor: 'app', volume_size: '50' }
    - name: Create OCP cluster
      include: ./tasks/rhel-instance-provider.yml
      with_items:
        - { instancename: 'lb1', flavor: 'lb', volume_size: '20' }
        - { instancename: 'lb2', flavor: 'lb', volume_size: '20' }
        - { instancename: 'bastion', flavor: 'bastion', volume_size: '50' }
